EFarming.Web/Controllers/ActuatorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;
using EFarming.Models;
using EFarming.Repository;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using JsonSerializer = Newtonsoft.Json.JsonSerializer;

namespace EFarming.Web.Controllers
{
    public class ActuatorController : Controller
    {
        private readonly HttpClient _httpClient;

        public ActuatorController()
        {
            _httpClient = new HttpClient();
        }

        // GET: Actuator
        public async Task<ActionResult> Index()
        {
            HttpResponseMessage response = await _httpClient.GetAsync("http://localhost:5005/api/actuators/");

            if (response.IsSuccessStatusCode)
            {
                var data = await response.Content.ReadAsStringAsync();
                var list = JsonConvert.DeserializeObject<List<Actuator>>(data);

                foreach (var item in list)
                {
                    HttpResponseMessage zoneResponse = await _httpClient
                        .GetAsync($"http://localhost:5005/api/farmzones/{item.FarmZoneId}");

                    var zoneData = await zoneResponse.Content.ReadAsStringAsync();
                    item.FarmZone = JsonConvert.DeserializeObject<FarmZone>(zoneData);
                }
                
                return View(list);
            }

            ModelState.AddModelError("", "Error while retrieving data.");
            return View();
        }

        // GET: Actuator/Details/5
        public async Task<ActionResult> Details(int id)
        {
            HttpResponseMessage response = await _httpClient.GetAsync($"http://localhost:5005/api/actuators/{id}");

            if (response.IsSuccessStatusCode)
            {
                var data = await response.Content.ReadAsStringAsync();
                var model = JsonConvert.DeserializeObject<Actuator>(data);
                
                HttpResponseMessage zoneResponse = await _httpClient
                    .GetAsync($"http://localhost:5005/api/farmzones/"+model.FarmZoneId);
                
                var zoneData = await zoneResponse.Content.ReadAsStringAsync();
                model.FarmZone = JsonConvert.DeserializeObject<FarmZone>(zoneData);
                
                return View(model);
            }

            ModelState.AddModelError("", "Error while retrieving data.");
            return View();
        }

        // GET: Actuator/Create
        public async Task<ActionResult> Create()
        {
            HttpResponseMessage response = await _httpClient.GetAsync("http://localhost:5005/api/farmzones");

            if (response.IsSuccessStatusCode)
            {
                var data = await response.Content.ReadAsStringAsync();
                ViewBag.Zones = JsonConvert.DeserializeObject<List<FarmZone>>(data);
            }

            return View();
        }

        // POST: Actuator/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Actuator actuator)
        {
            string json = JsonConvert.SerializeObject(actuator);
            using (var content = new StringContent
                (json, Encoding.UTF8, "application/json"))
            {
                HttpResponseMessage result =
                    await _httpClient.PostAsync("http://localhost:5005/api/actuators/", content);

                if (result.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
            }

            ModelState.AddModelError("", "Error while creating data.");
            return View();
        }

        // GET: Actuator/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            HttpResponseMessage farmResponse = await _httpClient.GetAsync("http://localhost:5005/api/farmzones");

            if (farmResponse.IsSuccessStatusCode)
            {
                var data = await farmResponse.Content.ReadAsStringAsync();
                ViewBag.Zones = Newtonsoft.Json.JsonConvert.DeserializeObject<List<FarmZone>>(data);
            }

            HttpResponseMessage response = await _httpClient.GetAsync($"http://localhost:5005/api/actuators/{id}");

            if (response.IsSuccessStatusCode)
            {
                var data = await response.Content.ReadAsStringAsync();
                var model = Newtonsoft.Json.JsonConvert.DeserializeObject<Actuator>(data);

                return View(model);
            }

            ModelState.AddModelError("", "Error while retrieving data.");
            return View();
        }

        // POST: Actuator/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, Actuator actuator)
        {
            string json = JsonConvert.SerializeObject(actuator);
            using (var content = new StringContent
                (json, Encoding.UTF8, "application/json"))
            {
                HttpResponseMessage result =
                    await _httpClient.PutAsync($"http://localhost:5005/api/actuators/{actuator.Id}", content);

                if (result.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
            }

            ModelState.AddModelError("", "Error while creating data.");
            return View();
        }

        // GET: Actuator/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            HttpResponseMessage response = await _httpClient.GetAsync($"http://localhost:5005/api/actuators/{id}");

            if (response.IsSuccessStatusCode)
            {
                var data = await response.Content.ReadAsStringAsync();
                var model = Newtonsoft.Json.JsonConvert.DeserializeObject<Actuator>(data);

                return View(model);
            }

            ModelState.AddModelError("", "Error while retrieving data.");
            return View();
        }

        // POST: Actuator/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, IFormCollection collection)
        {
            string json = JsonConvert.SerializeObject(id);
            using (var content = new StringContent
                (json, Encoding.UTF8, "application/json"))
            {
                HttpResponseMessage result =
                    await _httpClient.DeleteAsync($"http://localhost:5005/api/actuators/{id}");

                if (result.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
            }

            ModelState.AddModelError("", "Error while creating data.");
            return View();
        }
    }
}

EFarming.Web/Controllers/SensorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using EFarming.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace EFarming.Web.Controllers
{
    public class SensorController : Controller
    {
        private readonly HttpClient _httpClient;

        public SensorController()
        {
            _httpClient = new HttpClient();
        }
        
        // GET: Sensor
        public async Task<ActionResult> Index()
        {
            HttpResponseMessage response = await _httpClient.GetAsync("http://localhost:5005/api/sensors/");

            if (response.IsSuccessStatusCode)
            {
                var data = await response.Content.ReadAsStringAsync();
                var list = Newtonsoft.Json.JsonConvert.DeserializeObject<List<Sensor>>(data);

                return View(list);
            }

            ModelState.AddModelError("", "Error while retrieving data.");
            return View();
        }

        // GET: Sensor/Details/5
        public async Task<ActionResult> Details(int id)
        {
            HttpResponseMessage response = await _httpClient.GetAsync($"http://localhost:5005/api/sensors/{id}");

            if (response.IsSuccessStatusCode)
            {
                var data = await response.Content.ReadAsStringAsync();
                var model = Newtonsoft.Json.JsonConvert.DeserializeObject<Sensor>(data);

                return View(model);
            }

            ModelState.AddModelError("", "Error while retrieving data.");
            return View();
        }

        // GET: Sensor/Create
        public ActionResult Create()
        {
            // var sensor = new Sensor
            // {
            //     SensorTypes = Enum.GetValues(typeof(SensorType)).Cast<SensorType>()
            // };
            
            return View();
        }

        // POST: Sensor/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Sensor sensor)
        {
            string json = JsonConvert.SerializeObject(sensor);
            using (var content = new StringContent
                (json, Encoding.UTF8, "application/json"))
            {
                HttpResponseMessage result = 
                    await _httpClient.PostAsync("http://localhost:5005/api/sensors/", content);
                
                if (result.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
            }
            
            ModelState.AddModelError("", "Error while creating data.");
            return View();
        }

        // GET: Sensor/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            HttpResponseMessage response = await _httpClient.GetAsync($"http://localhost:5005/api/sensors/{id}");

            if (response.IsSuccessStatusCode)
            {
                var data = await response.Content.ReadAsStringAsync();
                var model = Newtonsoft.Json.JsonConvert.DeserializeObject<Sensor>(data);

                return View(model);
            }

            ModelState.AddModelError("", "Error while retrieving data.");
            return View();
        }

        // POST: Sensor/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, Sensor sensor)
        {
            string json = JsonConvert.SerializeObject(sensor);
            using (var content = new StringContent
                (json, Encoding.UTF8, "application/json"))
            {
                HttpResponseMessage result =
                    await _httpClient.PutAsync($"http://localhost:5005/api/sensors/{sensor.Id}", content);
                
                if (result.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
            }
            
            ModelState.AddModelError("", "Error while creating data.");
            return View();
        }

        // GET: Sensor/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            HttpResponseMessage response = await _httpClient.GetAsync($"http://localhost:5005/api/sensors/{id}");

            if (response.IsSuccessStatusCode)
            {
                var data = await response.Content.ReadAsStringAsync();
                var model = Newtonsoft.Json.JsonConvert.DeserializeObject<Sensor>(data);

                return View(model);
            }

            ModelState.AddModelError("", "Error while retrieving data.");
            return View();
        }

        // POST: Sensor/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, IFormCollection collection)
        {
            string json = JsonConvert.SerializeObject(id);
            using (var content = new StringContent
                (json, Encoding.UTF8, "application/json"))
            {
                HttpResponseMessage result =
                    await _httpClient.DeleteAsync($"http://localhost:5005/api/sensors/{id}");
                
                if (result.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
            }
            
            ModelState.AddModelError("", "Error while creating data.");
            return View();
        }
    }
}

EFarming.Web/Views/Actuator/Create.cshtml
@model EFarming.Models.Actuator

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Actuator</h4>
<hr/>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @* <div class="form-group"> *@
            @*     <label asp-for="Id" class="control-label"></label> *@
            @*     <input asp-for="Id" class="form-control" /> *@
            @*     <span asp-validation-for="Id" class="text-danger"></span> *@
            @* </div> *@
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control"/>
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Latitude" class="control-label"></label>
                <input asp-for="Latitude" class="form-control"/>
                <span asp-validation-for="Latitude" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Longitude" class="control-label"></label>
                <input asp-for="Longitude" class="form-control"/>
                <span asp-validation-for="Longitude" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CriticalValue" class="control-label"></label>
                <input asp-for="CriticalValue" class="form-control"/>
                <span asp-validation-for="CriticalValue" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsOpen"/> @Html.DisplayNameFor(model => model.IsOpen)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="ValveOpenTime" class="control-label"></label>
                <input asp-for="ValveOpenTime" class="form-control"/>
                <span asp-validation-for="ValveOpenTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WaterFlowRate" class="control-label"></label>
                <input asp-for="WaterFlowRate" class="form-control"/>
                <span asp-validation-for="WaterFlowRate" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsGoodCondition"/> @Html.DisplayNameFor(model => model.IsGoodCondition)
                </label>
            </div>
            @* <div class="form-group"> *@
            @*     <label asp-for="FarmZoneId" class="control-label"></label> *@
            @*     <input asp-for="FarmZoneId" class="form-control" /> *@
            @*     <span asp-validation-for="FarmZoneId" class="text-danger"></span> *@
            @* </div> *@
            <div class="form-group">
                @Html.LabelFor(model => model.FarmZone, "Zone", htmlAttributes: new {@class = "control-label col-md-2"})
                <div class="col-md-4">
                    @Html.ValidationMessageFor(model => model.FarmZoneId, "", new {@class = "text-danger"})
                    @Html.DropDownListFor(x => x.FarmZoneId, new SelectList(ViewBag.Zones, "ZoneId", "FullName"), " ")
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

EFarming.Web/Views/Actuator/Delete.cshtml
@model EFarming.Models.Actuator

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Actuator</h4>
    <hr />
    <dl class="row">
        @* <dt class = "col-sm-2"> *@
        @*     @Html.DisplayNameFor(model => model.Id) *@
        @* </dt> *@
        @* <dd class = "col-sm-10"> *@
        @*     @Html.DisplayFor(model => model.Id) *@
        @* </dd> *@
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Latitude)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Latitude)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Longitude)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Longitude)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CriticalValue)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CriticalValue)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsOpen)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsOpen)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ValveOpenTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ValveOpenTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WaterFlowRate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WaterFlowRate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsGoodCondition)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsGoodCondition)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FarmZoneId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FarmZoneId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

EFarming.Web/Views/Actuator/Details.cshtml
@model EFarming.Models.Actuator

@{
    ViewData["Title"] = "Details";
}

<div>
    <h4>Actuator</h4>
    <hr/>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Latitude)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Latitude)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Longitude)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Longitude)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CriticalValue)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CriticalValue)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IsOpen)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IsOpen)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ValveOpenTime)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ValveOpenTime)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.WaterFlowRate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.WaterFlowRate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IsGoodCondition)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IsGoodCondition)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FarmZoneId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FarmZoneId)
        </dd>
    </dl>
</div>
<div>
    <table class="table">
        <thead>
            <tr>
            <th>Name</th>
            <th>Type</th>
            <th>Latitude</th>
            <th>Longitude</th>
            <th>Critical Value</th>
            <th>Signal</th>
            <th>CreatedAt</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @foreach (var item in Model.Sensors)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Type)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Latitude)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Longitude)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CriticalValue)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit",  "Sensor", new {id = item.Id}) |
                    @Html.ActionLink("Details", "Details", "Sensor",new {id = item.Id}) |
                    @Html.ActionLink("Delete", "Delete",  "Sensor",new {id = item.Id})
                </td>
            </tr>
        }
        </tbody>
    </table>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new {id = Model.Id}) |
    <a asp-action="Index">Back to List</a>
</div>

EFarming.Web/Views/Actuator/Edit.cshtml
@model EFarming.Models.Actuator

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Actuator</h4>
<hr/>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @* <div class="form-group"> *@
            @*     <label asp-for="Id" class="control-label"></label> *@
            @*     <input asp-for="Id" class="form-control" /> *@
            @*     <span asp-validation-for="Id" class="text-danger"></span> *@
            @* </div> *@
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control"/>
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Latitude" class="control-label"></label>
                <input asp-for="Latitude" class="form-control"/>
                <span asp-validation-for="Latitude" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Longitude" class="control-label"></label>
                <input asp-for="Longitude" class="form-control"/>
                <span asp-validation-for="Longitude" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CriticalValue" class="control-label"></label>
                <input asp-for="CriticalValue" class="form-control"/>
                <span asp-validation-for="CriticalValue" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsOpen"/> @Html.DisplayNameFor(model => model.IsOpen)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="ValveOpenTime" class="control-label"></label>
                <input asp-for="ValveOpenTime" class="form-control"/>
                <span asp-validation-for="ValveOpenTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WaterFlowRate" class="control-label"></label>
                <input asp-for="WaterFlowRate" class="form-control"/>
                <span asp-validation-for="WaterFlowRate" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsGoodCondition"/> @Html.DisplayNameFor(model => model.IsGoodCondition)
                </label>
            </div>
            @* <div class="form-group"> *@
            @*     <label asp-for="FarmZoneId" class="control-label"></label> *@
            @*     <input asp-for="FarmZoneId" class="form-control" /> *@
            @*     <span asp-validation-for="FarmZoneId" class="text-danger"></span> *@
            @* </div> *@
            <div class="form-group">
                @Html.LabelFor(model => model.FarmZone, "Zone", htmlAttributes: new {@class = "control-label col-md-2"})
                <div class="col-md-4">
                    @Html.ValidationMessageFor(model => model.FarmZoneId, "", new {@class = "text-danger"})
                    @Html.DropDownListFor(x => x.FarmZoneId, new SelectList(ViewBag.Zones, "ZoneId", "FullName"), " ")
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

EFarming.Web/Views/Actuator/Index.cshtml
@model IEnumerable<EFarming.Models.Actuator>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Latitude)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Longitude)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CriticalValue)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsOpen)
            </th>
             <th> 
                 @Html.DisplayNameFor(model => model.ValveOpenTime) 
             </th> 
            <th>
                @Html.DisplayNameFor(model => model.WaterFlowRate)
            </th>
             <th> 
                 @Html.DisplayNameFor(model => model.IsGoodCondition) 
             </th> 
            <th>
                @Html.DisplayNameFor(model => model.FarmZone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sensors)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Latitude)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Longitude)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CriticalValue)
            </td>
            <td class="valveState">
                @Html.DisplayFor(modelItem => item.IsOpen)
                @if (item.IsOpen)
                {
                    <p class="valveIsOpenText">Open</p>
                }
                else
                {
                    <p class="valveIsClosedText">Closed</p>
                }
            </td>
             <td> 
                 @Html.DisplayFor(modelItem => item.ValveOpenTime) 
             </td> 
            <td>
                @Html.DisplayFor(modelItem => item.WaterFlowRate)
            </td>
             <td> 
                 @Html.DisplayFor(modelItem => item.IsGoodCondition) 
             </td> 
            <td>
                @Html.DisplayFor(modelItem => item.FarmZone.FullName)
            </td>
            <td>
                @if(item.Sensors.Count > 0)
                {
                <ul>
                    @foreach(var sensor in item.Sensors)
                    {
                        <li>
                            @sensor.Name with Id: @sensor.Id
                        </li>
                    }
                </ul>
                }
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", "Actuator", new { id=item.Id }) |
                @Html.ActionLink("Details", "Details", "Actuator",new { id=item.Id }) |
                @Html.ActionLink("Delete", "Delete","Actuator", new { id=item.Id })
            </td>
        </tr>
}
    </tbody>
</table>